### ISSUE TITLE
Dev server throws an error before first build

### ISSUE THREAD

**Issue by isUnknown** [arnoson/kirby-vite-multi-page-kit#12]
The dist folder doesn't exist yet before the first build so the dev server throws an error, trying to find the `manifest.json`.
```
 Exception
manifest.json not found.
```

You could provide a default dist folder or at least indicate to first run a build before running the dev server.

**Comment by arnoson** [comment]
Thats' strange, the manifest and dist folder shouldn't be needed at all during development. Does the error occur after you run `npm run dev`? I'm travelling right now, but will look into this next week.

**Comment by isUnknown** [comment]
Yep, after running `npm run dev`. I had more informations but unfortunatly I removed the clone, it was just a little try. I remember that a line of code was trying to find the `dist/` folder.

**Comment by arnoson** [comment]
I could reproduce your error, thanks for the good catch! I added a feature recently to check if a template entry exists. This feature tried to access the `manifest.json` during development and caused the error. Because this feature also caused other problems I dropped the approach in favour of a more verbose but also more flexible way of including template entries.
