### ISSUE TITLE
Ability to run without an template entry

### ISSUE THREAD

**Issue by bogdancondorachi** [arnoson/kirby-vite-multi-page-kit#9]
Hello, I'm using this setup because I want to have separate js entry on some of the pages besides the shared one. All is fine for now except for the fact that the setup seems to require an entry on all my templates.

In my scenario, I'm using a shared entry on every template and on some of the templates running a specific one but I have no use of one in all of my templates and if the entry is missing kirby vite is throws me an error: ``templates/home/index.jsx` is not a manifest entry.`.

Would be nice if the system can check if a template entry is available or not and list the specific entry accordingly.

**Comment by arnoson** [comment]
Right now there is no way to check if an entry exists before trying to include it and I'm not sure if it would be a good idea to add such a check, because your normally know which entry exists beforehand.

What I've been using in such cases is to modify the header/footer snippet a bit and explicitly pass (or omit) the entry name:

```php
// snippets/header.php

<head>
  <!-- Include the shared css ... -->
  <?= vite()->css() ?>
  <!-- ... and the template's css -->
  <?php if($entry ?? false) {
    echo vite()->css("templates/$entry/index.js");
  }?>
</head>
<body>
  <?php snippet('menu') ?>
```

and then use it like this
```php
snippet('header', ['entry' => 'about'])
```
or this

```php
// Omit the entry, so only the shared js/css is included
snippet('header')
```

The footer snippet would have to be adjusted accordingly.
